# ============================================================

# AUTO-GENERATED CODE - DO NOT EDIT

# Generated by Pfn compiler

# Generated at: 2026-03-01 09:54:49

# ============================================================



from __future__ import annotations

from stdlib import String, List, Dict, Set, Maybe, Result, Just, Nothing, Ok, Err, Record

from stdlib import reverse, _not_

from bootstrap.Token import *

from bootstrap.Lexer import *

from bootstrap.AST import *

from bootstrap.Parser import *

from bootstrap.Types import *

from bootstrap.TypeChecker import *

from bootstrap.Codegen import *

def compile(source):
    return (lambda __match_val: ((Err('Lexer error: ' + __match_val._field0.message) if isinstance(__match_val, Err) else None)) or (((lambda __match_val: ((Err('Parser error: ' + errorToString(__match_val._field0)) if isinstance(__match_val, Err) else None)) or (((typeCheckResult := (typeCheckModule(__match_val._field0))) is not None and (lambda __match_val: ((Err('Type error: ' + __match_val._field0.message) if isinstance(__match_val, Err) else None)) or (((pythonCode := (generateModule(__match_val._field0))) is not None and Ok(pythonCode) if isinstance(__match_val, Ok) else None)))(typeCheckResult) if isinstance(__match_val, Ok) else None)))(parse(__match_val._field0)) if isinstance(__match_val, Ok) else None)))(tokenize(source))

def typeCheckModule(mod):
    return typeCheckDecls(mod.declarations)(initTypeChecker)

def typeCheckDecls(decls):
    return lambda state: (lambda __match_val: ((Ok(None) if __match_val == [] else None)) or (((lambda __match_val: ((typeCheckDecls(__match_val[1:])(state) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((typeCheckDecls(__match_val[1:])(state) if isinstance(__match_val, list) and len(__match_val) > 0 else None)))(inferLetFunc(state)(emptySubst)(__match_val[0]._field0.name)(__match_val[0]._field0.params)(__match_val[0]._field0.body)(UnitLit)) if isinstance(__match_val, list) and len(__match_val) > 0 and isinstance(__match_val[0], DefDecl) else None)))(decls)

def compileAndPrint(source):
    return (lambda __match_val: (('Generated Python:\n' + __match_val._field0 if isinstance(__match_val, Ok) else None)) or (('Error: ' + __match_val._field0 if isinstance(__match_val, Err) else None)))(compile(source))

example = (source := ('def add x y = x + y')) is not None and compileAndPrint(source)

main = 'Pfn Bootstrap Compiler\n\n' + example