# ============================================================

# AUTO-GENERATED CODE - DO NOT EDIT

# Generated by Pfn compiler

# Generated at: 2026-02-28 21:52:37

# ============================================================



from __future__ import annotations

from stdlib import String, List, Dict, Set, Maybe, Result, Just, Nothing, Ok, Err, Record

from stdlib import reverse, _not_

from bootstrap.Token import *

from bootstrap.Lexer import *

from bootstrap.AST import *

from bootstrap.Parser import *

from bootstrap.Types import *

from bootstrap.TypeChecker import *

from bootstrap.Codegen import *

def compile(source):
    return __helper_2(tokenize(source))

def typeCheckModule(mod):
    return typeCheckDecls(mod.declarations)(initTypeChecker)

def typeCheckDecls(decls):
    return lambda state: __helper_4(decls)

def compileAndPrint(source):
    return __helper_5(compile(source))

example = ((compileAndPrint(source)) if (source := ('def add x y = x + y')) is not None else None)

main = 'Pfn Bootstrap Compiler\n\n' + example


# Helper functions to avoid deep nesting
def __helper_0(__match_val):
    return ((Err('Type error: ' + __match_val._field0.message) if isinstance(__match_val, Err) else None)) or ((((Ok(pythonCode)) if (pythonCode := (generateModule(mod))) is not None else None) if isinstance(__match_val, Ok) else None))
def __helper_1(__match_val):
    return ((Err('Parser error: ' + errorToString(__match_val._field0)) if isinstance(__match_val, Err) else None)) or ((((__helper_0(typeCheckResult)) if (typeCheckResult := (typeCheckModule(__match_val._field0))) is not None else None) if isinstance(__match_val, Ok) else None))
def __helper_2(__match_val):
    return ((Err('Lexer error: ' + __match_val._field0.message) if isinstance(__match_val, Err) else None)) or ((__helper_1(parse(__match_val._field0)) if isinstance(__match_val, Ok) else None))
def __helper_3(__match_val):
    return ((typeCheckDecls(rest)(state) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((typeCheckDecls(__match_val[1:])(state) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_4(__match_val):
    return ((Ok(None) if __match_val == [] else None)) or ((__helper_3(inferLetFunc(state)(emptySubst)(__match_val[0]._field0.name)(__match_val[0]._field0.params)(__match_val[0]._field0.body)(UnitLit)) if isinstance(__match_val, list) and len(__match_val) > 0 and isinstance(__match_val[0], DefDecl) else None))
def __helper_5(__match_val):
    return (('Generated Python:\n' + __match_val._field0 if isinstance(__match_val, Ok) else None)) or (('Error: ' + __match_val._field0 if isinstance(__match_val, Err) else None))