# ============================================================

# AUTO-GENERATED CODE - DO NOT EDIT

# Generated by Pfn compiler

# Generated at: 2026-02-28 21:52:37

# ============================================================



from __future__ import annotations

from stdlib import String, List, Dict, Set, Maybe, Result, Just, Nothing, Ok, Err, Record

from stdlib import reverse, _not_

from bootstrap.Types import *

from bootstrap.AST import *

from dataclasses import dataclass

@dataclass
class TypeError:
    message: str

def typeError(message):
    return Record({"message": message})

from dataclasses import dataclass

@dataclass
class TypeCheckerState:
    env: TypeEnv
    varCounter: int

initTypeChecker = Record({"env": emptyEnv, "varCounter": 0})

def freshVar(state):
    return (((tVar(name), Record({**state, "varCounter": state.varCounter + 1}))) if (name := ('t' + toString(state.varCounter + 1))) is not None else None)

def instantiate(state):
    return lambda scheme: (scheme.typ, state) if List.isEmpty(scheme.vars) else instantiateVars(state)(scheme.vars)(emptySubst)(scheme.typ)

def instantiateVars(state):
    return lambda vars: lambda subst: lambda t: __helper_1(vars)

def generalize(env):
    return lambda t: ((((((Record({"vars": genVars, "typ": t})) if (genVars := (Set.toList(Set.difference(typeVars)(envVars)))) is not None else None)) if (typeVars := (freeVars(t))) is not None else None)) if (envVars := (freeVarsEnv(env))) is not None else None)

from dataclasses import dataclass

@dataclass
class InferResult:
    typ: Type
    subst: Subst
    state: TypeCheckerState

def inferResult(t):
    return lambda subst: lambda state: Record({"typ": t, "subst": subst, "state": state})

def infer(state):
    return lambda expr: inferExpr(state)(emptySubst)(expr)

def inferExpr(state):
    return lambda subst: lambda expr: __helper_6(expr)

def inferLambda(state):
    return lambda subst: lambda params: lambda body: lambda paramTypes: __helper_8(params)

def inferLambdaBody(state):
    return lambda subst: lambda paramTypes: lambda body: __helper_9(inferExpr(state)(subst)(body))

def buildFunType(params):
    return lambda result: __helper_10(params)

def inferApp(state):
    return lambda subst: lambda func: lambda args: __helper_11(inferExpr(state)(subst)(func))

def inferAppArgs(state):
    return lambda subst: lambda funcType: lambda args: __helper_15(args)

def inferBinOp(state):
    return lambda subst: lambda left: lambda op: lambda right: __helper_17(inferExpr(state)(subst)(left))

def inferBinOpType(state):
    return lambda subst: lambda leftType: lambda op: lambda rightType: inferArithOp(state)(subst)(leftType)(rightType) if List.member(op)(['+', '-', '*', '/', '%']) else inferComparisonOp(state)(subst)(leftType)(rightType) if List.member(op)(['<', '<=', '>', '>=']) else inferEqualityOp(state)(subst)(leftType)(rightType) if List.member(op)(['==', '!=']) else inferBooleanOp(state)(subst)(leftType)(rightType) if List.member(op)(['&&', '||']) else inferConcatOp(state)(subst)(leftType)(rightType) if op == '++' else inferConsOp(state)(subst)(leftType)(rightType) if op == '::' else Err(typeError('Unknown operator: ' + op))

def inferArithOp(state):
    return lambda subst: lambda leftType: lambda rightType: __helper_23(unify(applySubst(subst)(leftType))(TInt))

def inferComparisonOp(state):
    return lambda subst: lambda leftType: lambda rightType: __helper_27(unify(applySubst(subst)(leftType))(TInt))

def inferEqualityOp(state):
    return lambda subst: lambda leftType: lambda rightType: __helper_28(unify(applySubst(subst)(leftType))(applySubst(subst)(rightType)))

def inferBooleanOp(state):
    return lambda subst: lambda leftType: lambda rightType: __helper_30(unify(applySubst(subst)(leftType))(TBool))

def inferConcatOp(state):
    return lambda subst: lambda leftType: lambda rightType: __helper_33(freshVar(state))

def inferConsOp(state):
    return lambda subst: lambda leftType: lambda rightType: __helper_34(unify(applySubst(subst)(rightType))(tList(leftType)))

def inferUnaryOp(state):
    return lambda subst: lambda op: lambda operand: __helper_38(inferExpr(state)(subst)(operand))

def inferIf(state):
    return lambda subst: lambda cond: lambda thenBranch: lambda elseBranch: __helper_43(inferExpr(state)(subst)(cond))

def inferLet(state):
    return lambda subst: lambda name: lambda value: lambda body: __helper_45(inferExpr(state)(subst)(value))

def inferLetFunc(state):
    return lambda subst: lambda name: lambda params: lambda value: lambda body: inferLetFuncParams(state)(subst)(params)([])(value)(lambda s: lambda pt: lambda vt: ((((((__helper_46(inferExpr(Record({**s, "env": newEnv}))(subst)(body))) if (newEnv := (extendEnv(s.env)(name)(scheme))) is not None else None)) if (scheme := (generalize(s.env)(funcType))) is not None else None)) if (funcType := (buildFunType(pt)(vt))) is not None else None))

def inferLetFuncParams(state):
    return lambda subst: lambda params: lambda paramTypes: lambda value: lambda cont: __helper_49(params)

def inferList(state):
    return lambda subst: lambda elements: __helper_52(elements)

def inferListElements(state):
    return lambda subst: lambda elemType: lambda elements: __helper_55(elements)

def inferTuple(state):
    return lambda subst: lambda elements: inferTupleElements(state)(subst)([])(elements)

def inferTupleElements(state):
    return lambda subst: lambda types: lambda elements: __helper_57(elements)

def inferMatch(state):
    return lambda subst: lambda scrutinee: lambda cases: __helper_60(inferExpr(state)(subst)(scrutinee))

def inferMatchCases(state):
    return lambda subst: lambda scrutineeType: lambda resultType: lambda cases: __helper_65(cases)

def inferPattern(state):
    return lambda subst: lambda pattern: __helper_69(pattern)

def inferListPattern(state):
    return lambda subst: lambda elements: __helper_73(elements)

def inferListPatternElements(state):
    return lambda subst: lambda elemType: lambda env: lambda elements: __helper_76(elements)

def inferConsPattern(state):
    return lambda subst: lambda head: lambda tail: __helper_79(inferPattern(state)(subst)(head))

def inferTuplePattern(state):
    return lambda subst: lambda elements: inferTuplePatternElements(state)(subst)([])(emptyEnv)(elements)

def inferTuplePatternElements(state):
    return lambda subst: lambda types: lambda env: lambda elements: __helper_81(elements)

def inferIndexAccess(state):
    return lambda subst: lambda expr: lambda index: __helper_85(inferExpr(state)(subst)(expr))

def mergeEnv(e1):
    return lambda e2: Record({"bindings": Dict.merge(e1.bindings)(e2.bindings)})


# Helper functions to avoid deep nesting
def __helper_0(__let_val_0):
    return (lambda tv, s1: ((instantiateVars(s1)(rest)(newSubst)(t)) if (newSubst := (composeSubst(singletonSubst(v)(tv))(subst))) is not None else None))(__let_val_0[0], __let_val_0[1]) if isinstance(__let_val_0, tuple) and len(__let_val_0) == 2 else None
def __helper_1(__match_val):
    return (((applySubst(subst)(t), state) if __match_val == [] else None)) or ((__helper_0(freshVar(state)) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_2(__let_val_1):
    return (lambda t, s1: Ok(inferResult(t)(subst)(s1)))(__let_val_1[0], __let_val_1[1]) if isinstance(__let_val_1, tuple) and len(__let_val_1) == 2 else None
def __helper_3(__let_val_2):
    return (lambda tv, s1: Ok(inferResult(tv)(subst)(s1)))(__let_val_2[0], __let_val_2[1]) if isinstance(__let_val_2, tuple) and len(__let_val_2) == 2 else None
def __helper_4(__let_val_3):
    return (lambda tv, s1: Ok(inferResult(tv)(subst)(s1)))(__let_val_3[0], __let_val_3[1]) if isinstance(__let_val_3, tuple) and len(__let_val_3) == 2 else None
def __helper_5(__match_val):
    return ((__helper_2(instantiate(state)(__match_val._field0)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Unbound variable: ' + name)) if __match_val is Nothing else None)) or ((inferLambda(state)(subst)(__match_val._field0.params)(__match_val._field0.body)([]) if isinstance(__match_val, Lambda) else None)) or ((inferApp(state)(subst)(__match_val._field0.func)(__match_val._field0.args) if isinstance(__match_val, App) else None)) or ((inferBinOp(state)(subst)(__match_val._field0.left)(__match_val._field0.op)(__match_val._field0.right) if isinstance(__match_val, BinOp) else None)) or ((inferUnaryOp(state)(subst)(__match_val._field0.op)(__match_val._field0.operand) if isinstance(__match_val, UnaryOp) else None)) or ((inferIf(state)(subst)(__match_val._field0.cond)(__match_val._field0.thenBranch)(__match_val._field0.elseBranch) if isinstance(__match_val, If) else None)) or ((inferLet(state)(subst)(__match_val._field0.name)(__match_val._field0.value)(__match_val._field0.body) if isinstance(__match_val, Let) else None)) or ((inferLetFunc(state)(subst)(__match_val._field0.name)(__match_val._field0.params)(__match_val._field0.value)(__match_val._field0.body) if isinstance(__match_val, LetFunc) else None)) or ((inferList(state)(subst)(__match_val._field0) if isinstance(__match_val, ListLit) else None)) or ((inferTuple(state)(subst)(__match_val._field0) if isinstance(__match_val, TupleLit) else None)) or ((inferMatch(state)(subst)(__match_val._field0.scrutinee)(__match_val._field0.cases) if isinstance(__match_val, Match) else None)) or ((__helper_3(freshVar(state)) if isinstance(__match_val, FieldAccess) else None)) or ((inferIndexAccess(state)(subst)(__match_val._field0.expr)(__match_val._field0.index) if isinstance(__match_val, IndexAccess) else None)) or (__helper_4(freshVar(state)))
def __helper_6(__match_val):
    return ((Ok(inferResult(TInt)(subst)(state)) if isinstance(__match_val, IntLit) else None)) or ((Ok(inferResult(TFloat)(subst)(state)) if isinstance(__match_val, FloatLit) else None)) or ((Ok(inferResult(TString)(subst)(state)) if isinstance(__match_val, StringLit) else None)) or ((Ok(inferResult(TChar)(subst)(state)) if isinstance(__match_val, CharLit) else None)) or ((Ok(inferResult(TBool)(subst)(state)) if isinstance(__match_val, BoolLit) else None)) or ((Ok(inferResult(TUnit)(subst)(state)) if __match_val is UnitLit else None)) or ((__helper_5(lookupEnv(state.env)(__match_val._field0)) if isinstance(__match_val, Var) else None))
def __helper_7(__let_val_4):
    return (lambda tv, s1: ((inferLambda(Record({**s1, "env": newEnv}))(subst)(rest)(body)(paramTypes + [tv])) if (newEnv := (extendEnv(s1.env)(p.name)(monoScheme(tv)))) is not None else None))(__let_val_4[0], __let_val_4[1]) if isinstance(__let_val_4, tuple) and len(__let_val_4) == 2 else None
def __helper_8(__match_val):
    return ((((inferLambdaBody(state)(subst)(paramTypes)(body)) if (resultType := (buildFunType(List.reverse(paramTypes))(applySubst(subst)(inferResult.typ)))) is not None else None) if __match_val == [] else None)) or ((__helper_7(freshVar(state)) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_9(__match_val):
    return ((((Ok(inferResult(resultType)(__match_val._field0.subst)(__match_val._field0.state))) if (resultType := (buildFunType(List.reverse(paramTypes))(__match_val._field0.typ))) is not None else None) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_10(__match_val):
    return ((result if __match_val == [] else None)) or ((tFun(__match_val[0])(buildFunType(__match_val[1:])(result)) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_11(__match_val):
    return ((inferAppArgs(__match_val._field0.state)(__match_val._field0.subst)(__match_val._field0.typ)(args) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_12(__match_val):
    return ((((inferAppArgs(s1)(composed)(applySubst(composed)(resultType))(rest)) if (composed := (composeSubst(__match_val._field0)(argResult.subst))) is not None else None) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Cannot apply function')) if __match_val is Nothing else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_13(__let_val_5):
    return (lambda resultType, s1: __helper_12(unify(applySubst(argResult.subst)(funcType))(tFun(applySubst(argResult.subst)(argResult.typ))(resultType))))(__let_val_5[0], __let_val_5[1]) if isinstance(__let_val_5, tuple) and len(__let_val_5) == 2 else None
def __helper_14(__match_val):
    return (__helper_13(freshVar(__match_val._field0.state)) if isinstance(__match_val, Ok) else None)
def __helper_15(__match_val):
    return ((Ok(inferResult(funcType)(subst)(state)) if __match_val == [] else None)) or ((__helper_14(inferExpr(state)(subst)(__match_val[0])) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_16(__match_val):
    return ((inferBinOpType(__match_val._field0.state)(__match_val._field0.subst)(leftResult.typ)(op)(__match_val._field0.typ) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_17(__match_val):
    return (__helper_16(inferExpr(__match_val._field0.state)(__match_val._field0.subst)(right)) if isinstance(__match_val, Ok) else None)
def __helper_18(__match_val):
    return ((Ok(inferResult(TFloat)(composeSubst(__match_val._field0)(composed))(state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Type mismatch in arithmetic')) if __match_val is Nothing else None)) or ((Err(typeError('Expected Int or Float')) if __match_val is Nothing else None))
def __helper_19(__match_val):
    return (((__helper_18(unify(applySubst(composed)(rightType))(TFloat))) if (composed := (composeSubst(__match_val._field0)(subst))) is not None else None) if isinstance(__match_val, Just) else None)
def __helper_20(__match_val):
    return ((Ok(inferResult(TFloat)(composeSubst(__match_val._field0)(composed2))(state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Type mismatch in arithmetic')) if __match_val is Nothing else None)) or ((Err(typeError('Expected Int or Float')) if __match_val is Nothing else None)) or ((__helper_19(unify(applySubst(subst)(leftType))(TFloat)) if __match_val is Nothing else None))
def __helper_21(__match_val):
    return (((__helper_20(unify(applySubst(composed2)(rightType))(TFloat))) if (composed2 := (composeSubst(__match_val._field0)(composed))) is not None else None) if isinstance(__match_val, Just) else None)
def __helper_22(__match_val):
    return ((Ok(inferResult(TInt)(composeSubst(__match_val._field0)(composed))(state)) if isinstance(__match_val, Just) else None)) or ((__helper_21(unify(applySubst(composed)(leftType))(TFloat)) if __match_val is Nothing else None))
def __helper_23(__match_val):
    return (((__helper_22(unify(applySubst(composed)(rightType))(TInt))) if (composed := (composeSubst(__match_val._field0)(subst))) is not None else None) if isinstance(__match_val, Just) else None)
def __helper_24(__match_val):
    return ((Ok(inferResult(TBool)(composeSubst(__match_val._field0)(composed))(state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Type mismatch in comparison')) if __match_val is Nothing else None)) or ((Err(typeError('Expected Int or Float')) if __match_val is Nothing else None))
def __helper_25(__match_val):
    return (((__helper_24(unify(applySubst(composed)(rightType))(TFloat))) if (composed := (composeSubst(__match_val._field0)(subst))) is not None else None) if isinstance(__match_val, Just) else None)
def __helper_26(__match_val):
    return ((Ok(inferResult(TBool)(composeSubst(__match_val._field0)(composed))(state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Type mismatch in comparison')) if __match_val is Nothing else None)) or ((__helper_25(unify(applySubst(subst)(leftType))(TFloat)) if __match_val is Nothing else None))
def __helper_27(__match_val):
    return (((__helper_26(unify(applySubst(composed)(rightType))(TInt))) if (composed := (composeSubst(__match_val._field0)(subst))) is not None else None) if isinstance(__match_val, Just) else None)
def __helper_28(__match_val):
    return ((Ok(inferResult(TBool)(composeSubst(__match_val._field0)(subst))(state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Type mismatch in equality')) if __match_val is Nothing else None))
def __helper_29(__match_val):
    return ((Ok(inferResult(TBool)(composeSubst(__match_val._field0)(composed))(state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Expected Bool')) if __match_val is Nothing else None)) or ((Err(typeError('Expected Bool')) if __match_val is Nothing else None))
def __helper_30(__match_val):
    return (((__helper_29(unify(applySubst(composed)(rightType))(TBool))) if (composed := (composeSubst(__match_val._field0)(subst))) is not None else None) if isinstance(__match_val, Just) else None)
def __helper_31(__match_val):
    return ((Ok(inferResult(tList(applySubst(composeSubst(__match_val._field0)(composed))(elemType)))(composeSubst(__match_val._field0)(composed))(s1)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Type mismatch in ++')) if __match_val is Nothing else None)) or ((Err(typeError('Expected List for ++')) if __match_val is Nothing else None))
def __helper_32(__match_val):
    return (((__helper_31(unify(applySubst(composed)(rightType))(tList(applySubst(composed)(elemType))))) if (composed := (composeSubst(__match_val._field0)(subst))) is not None else None) if isinstance(__match_val, Just) else None)
def __helper_33(__let_val_6):
    return (lambda elemType, s1: __helper_32(unify(applySubst(subst)(leftType))(tList(elemType))))(__let_val_6[0], __let_val_6[1]) if isinstance(__let_val_6, tuple) and len(__let_val_6) == 2 else None
def __helper_34(__match_val):
    return ((Ok(inferResult(tList(applySubst(composeSubst(__match_val._field0)(subst))(leftType)))(composeSubst(__match_val._field0)(subst))(state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Expected List for ::')) if __match_val is Nothing else None))
def __helper_35(__match_val):
    return ((Ok(inferResult(TFloat)(composeSubst(__match_val._field0)(result.subst))(result.state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Expected Int or Float for -')) if __match_val is Nothing else None))
def __helper_36(__match_val):
    return ((Ok(inferResult(TInt)(composeSubst(__match_val._field0)(result.subst))(result.state)) if isinstance(__match_val, Just) else None)) or ((__helper_35(unify(applySubst(result.subst)(result.typ))(TFloat)) if __match_val is Nothing else None))
def __helper_37(__match_val):
    return ((Ok(inferResult(TBool)(composeSubst(__match_val._field0)(result.subst))(result.state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Expected Bool for !')) if __match_val is Nothing else None))
def __helper_38(__match_val):
    return ((__helper_36(unify(applySubst(__match_val._field0.subst)(__match_val._field0.typ))(TInt)) if op == '-' else __helper_37(unify(applySubst(__match_val._field0.subst)(__match_val._field0.typ))(TBool)) if op == '!' else Err(typeError('Unknown unary operator: ' + op)) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_39(__match_val):
    return ((Ok(inferResult(applySubst(composeSubst(__match_val._field0)(elseResult.subst))(thenResult.typ))(composeSubst(__match_val._field0)(elseResult.subst))(elseResult.state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('If branches must have same type')) if __match_val is Nothing else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((Err(typeError('If condition must be Bool')) if __match_val is Nothing else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_40(__match_val):
    return (__helper_39(unify(applySubst(__match_val._field0.subst)(thenResult.typ))(__match_val._field0.typ)) if isinstance(__match_val, Ok) else None)
def __helper_41(__match_val):
    return (__helper_40(inferExpr(__match_val._field0.state)(__match_val._field0.subst)(elseBranch)) if isinstance(__match_val, Ok) else None)
def __helper_42(__match_val):
    return (((__helper_41(inferExpr(condResult.state)(composed1)(thenBranch))) if (composed1 := (composeSubst(__match_val._field0)(condResult.subst))) is not None else None) if isinstance(__match_val, Just) else None)
def __helper_43(__match_val):
    return (__helper_42(unify(applySubst(__match_val._field0.subst)(__match_val._field0.typ))(TBool)) if isinstance(__match_val, Ok) else None)
def __helper_44(__match_val):
    return ((Ok(__match_val._field0) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_45(__match_val):
    return (((((__helper_44(inferExpr(Record({**__match_val._field0.state, "env": newEnv}))(__match_val._field0.subst)(body))) if (newEnv := (extendEnv(__match_val._field0.state.env)(name)(scheme))) is not None else None)) if (scheme := (generalize(__match_val._field0.state.env)(applySubst(__match_val._field0.subst)(__match_val._field0.typ)))) is not None else None) if isinstance(__match_val, Ok) else None)
def __helper_46(__match_val):
    return ((Ok(__match_val._field0) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_47(__let_val_7):
    return (lambda tv, s1: ((inferLetFuncParams(Record({**s1, "env": newEnv}))(subst)(rest)(paramTypes + [tv])(value)(cont)) if (newEnv := (extendEnv(s1.env)(p.name)(monoScheme(tv)))) is not None else None))(__let_val_7[0], __let_val_7[1]) if isinstance(__let_val_7, tuple) and len(__let_val_7) == 2 else None
def __helper_48(__match_val):
    return ((cont(__match_val._field0.state)(paramTypes)(applySubst(__match_val._field0.subst)(__match_val._field0.typ)) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((__helper_47(freshVar(state)) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_49(__match_val):
    return (__helper_48(inferExpr(state)(subst)(value)) if __match_val == [] else None)
def __helper_50(__let_val_8):
    return (lambda tv, s1: Ok(inferResult(tList(tv))(subst)(s1)))(__let_val_8[0], __let_val_8[1]) if isinstance(__let_val_8, tuple) and len(__let_val_8) == 2 else None
def __helper_51(__match_val):
    return ((inferListElements(__match_val._field0.state)(__match_val._field0.subst)(__match_val._field0.typ)(rest) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_52(__match_val):
    return ((__helper_50(freshVar(state)) if __match_val == [] else None)) or ((__helper_51(inferExpr(state)(subst)(__match_val[0])) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_53(__match_val):
    return ((inferListElements(result.state)(composeSubst(__match_val._field0)(result.subst))(applySubst(composeSubst(__match_val._field0)(result.subst))(elemType))(rest) if isinstance(__match_val, Just) else None)) or ((Err(typeError('List elements must have same type')) if __match_val is Nothing else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_54(__match_val):
    return (__helper_53(unify(applySubst(__match_val._field0.subst)(elemType))(applySubst(__match_val._field0.subst)(__match_val._field0.typ))) if isinstance(__match_val, Ok) else None)
def __helper_55(__match_val):
    return ((Ok(inferResult(tList(elemType))(subst)(state)) if __match_val == [] else None)) or ((__helper_54(inferExpr(state)(subst)(__match_val[0])) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_56(__match_val):
    return ((inferTupleElements(__match_val._field0.state)(__match_val._field0.subst)([applySubst(__match_val._field0.subst)(__match_val._field0.typ)] + types)(rest) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_57(__match_val):
    return ((Ok(inferResult(tTuple(List.reverse(types)))(subst)(state)) if __match_val == [] else None)) or ((__helper_56(inferExpr(state)(subst)(__match_val[0])) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_58(__let_val_9):
    return (lambda tv, s1: Ok(inferResult(tv)(scrutineeResult.subst)(s1)))(__let_val_9[0], __let_val_9[1]) if isinstance(__let_val_9, tuple) and len(__let_val_9) == 2 else None
def __helper_59(__let_val_10):
    return (lambda resultType, s1: inferMatchCases(s1)(scrutineeResult.subst)(scrutineeResult.typ)(resultType)(cases))(__let_val_10[0], __let_val_10[1]) if isinstance(__let_val_10, tuple) and len(__let_val_10) == 2 else None
def __helper_60(__match_val):
    return ((__helper_58(freshVar(__match_val._field0.state)) if List.isEmpty(cases) else __helper_59(freshVar(__match_val._field0.state)) if isinstance(__match_val, Ok) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_61(__match_val):
    return ((inferMatchCases(bodyResult.state)(composeSubst(__match_val._field0)(bodyResult.subst))(applySubst(composeSubst(__match_val._field0)(bodyResult.subst))(scrutineeType))(applySubst(composeSubst(__match_val._field0)(bodyResult.subst))(resultType))(rest) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Match cases must have same type')) if __match_val is Nothing else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((Err(typeError('Pattern type mismatch')) if __match_val is Nothing else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_62(__match_val):
    return (__helper_61(unify(applySubst(__match_val._field0.subst)(resultType))(__match_val._field0.typ)) if isinstance(__match_val, Ok) else None)
def __helper_63(__match_val):
    return (((((__helper_62(inferExpr(Record({**state, "env": envWithPattern}))(composed)(c.body))) if (envWithPattern := (mergeEnv(state.env)(patternEnv))) is not None else None)) if (composed := (composeSubst(__match_val._field0)(s1))) is not None else None) if isinstance(__match_val, Just) else None)
def __helper_64(__match_val):
    return (__helper_63(unify(applySubst(__match_val._field0[2])(scrutineeType))(applySubst(__match_val._field0[2])(__match_val._field0[0]))) if isinstance(__match_val, Ok) and isinstance(__match_val._field0, tuple) and len(__match_val._field0) == 3 else None)
def __helper_65(__match_val):
    return ((Ok(inferResult(applySubst(subst)(resultType))(subst)(state)) if __match_val == [] else None)) or ((__helper_64(inferPattern(state)(subst)(__match_val[0].pattern)) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_66(__let_val_11):
    return (lambda tv, s1: Ok((tv, extendEnv(emptyEnv)(name)(monoScheme(tv)), subst)))(__let_val_11[0], __let_val_11[1]) if isinstance(__let_val_11, tuple) and len(__let_val_11) == 2 else None
def __helper_67(__let_val_12):
    return (lambda tv, s1: Ok((tv, emptyEnv, subst)))(__let_val_12[0], __let_val_12[1]) if isinstance(__let_val_12, tuple) and len(__let_val_12) == 2 else None
def __helper_68(__let_val_13):
    return (lambda tv, s1: Ok((tv, emptyEnv, subst)))(__let_val_13[0], __let_val_13[1]) if isinstance(__let_val_13, tuple) and len(__let_val_13) == 2 else None
def __helper_69(__match_val):
    return ((Ok((TInt, emptyEnv, subst)) if isinstance(__match_val, IntPattern) else None)) or ((Ok((TFloat, emptyEnv, subst)) if isinstance(__match_val, FloatPattern) else None)) or ((Ok((TString, emptyEnv, subst)) if isinstance(__match_val, StringPattern) else None)) or ((Ok((TChar, emptyEnv, subst)) if isinstance(__match_val, CharPattern) else None)) or ((Ok((TBool, emptyEnv, subst)) if isinstance(__match_val, BoolPattern) else None)) or ((__helper_66(freshVar(state)) if isinstance(__match_val, VarPattern) else None)) or ((__helper_67(freshVar(state)) if __match_val is WildcardPattern else None)) or ((inferListPattern(state)(subst)(__match_val._field0) if isinstance(__match_val, ListPattern) else None)) or ((inferConsPattern(state)(subst)(__match_val._field0.head)(__match_val._field0.tail) if isinstance(__match_val, ConsPattern) else None)) or ((inferTuplePattern(state)(subst)(__match_val._field0) if isinstance(__match_val, TuplePattern) else None)) or (__helper_68(freshVar(state)))
def __helper_70(__let_val_14):
    return (lambda tv, s1: Ok((tList(tv), emptyEnv, subst)))(__let_val_14[0], __let_val_14[1]) if isinstance(__let_val_14, tuple) and len(__let_val_14) == 2 else None
def __helper_71(__match_val):
    return ((Ok((tList(__match_val._field0[0]), __match_val._field0[1], __match_val._field0[2])) if isinstance(__match_val, Ok) and isinstance(__match_val._field0, tuple) and len(__match_val._field0) == 3 else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_72(__match_val):
    return (__helper_71(inferListPatternElements(state)(__match_val._field0[2])(__match_val._field0[0])(__match_val._field0[1])(rest)) if isinstance(__match_val, Ok) and isinstance(__match_val._field0, tuple) and len(__match_val._field0) == 3 else None)
def __helper_73(__match_val):
    return ((__helper_70(freshVar(state)) if __match_val == [] else None)) or ((__helper_72(inferPattern(state)(subst)(__match_val[0])) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_74(__match_val):
    return ((inferListPatternElements(state)(composeSubst(__match_val._field0)(s))(applySubst(composeSubst(__match_val._field0)(s))(elemType))(mergeEnv(env)(eEnv))(rest) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Pattern elements must have same type')) if __match_val is Nothing else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_75(__match_val):
    return (__helper_74(unify(applySubst(__match_val._field0[2])(elemType))(applySubst(__match_val._field0[2])(__match_val._field0[0]))) if isinstance(__match_val, Ok) and isinstance(__match_val._field0, tuple) and len(__match_val._field0) == 3 else None)
def __helper_76(__match_val):
    return ((Ok((elemType, env, subst)) if __match_val == [] else None)) or ((__helper_75(inferPattern(state)(subst)(__match_val[0])) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_77(__match_val):
    return ((Ok((tList(applySubst(composeSubst(__match_val._field0)(s2))(headType)), mergeEnv(headEnv)(tailEnv), composeSubst(__match_val._field0)(s2))) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Cons pattern type mismatch')) if __match_val is Nothing else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_78(__match_val):
    return (__helper_77(unify(applySubst(__match_val._field0[2])(__match_val._field0[0]))(tList(applySubst(__match_val._field0[2])(headType)))) if isinstance(__match_val, Ok) and isinstance(__match_val._field0, tuple) and len(__match_val._field0) == 3 else None)
def __helper_79(__match_val):
    return (__helper_78(inferPattern(state)(__match_val._field0[2])(tail)) if isinstance(__match_val, Ok) and isinstance(__match_val._field0, tuple) and len(__match_val._field0) == 3 else None)
def __helper_80(__match_val):
    return ((inferTuplePatternElements(state)(__match_val._field0[2])([applySubst(__match_val._field0[2])(__match_val._field0[0])] + types)(mergeEnv(env)(__match_val._field0[1]))(rest) if isinstance(__match_val, Ok) and isinstance(__match_val._field0, tuple) and len(__match_val._field0) == 3 else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_81(__match_val):
    return ((Ok((tTuple(List.reverse(types)), env, subst)) if __match_val == [] else None)) or ((__helper_80(inferPattern(state)(subst)(__match_val[0])) if isinstance(__match_val, list) and len(__match_val) > 0 else None))
def __helper_82(__let_val_15):
    return (lambda tv, s1: Ok(inferResult(tv)(composeSubst(s)(indexResult.subst))(s1)))(__let_val_15[0], __let_val_15[1]) if isinstance(__let_val_15, tuple) and len(__let_val_15) == 2 else None
def __helper_83(__match_val):
    return ((__helper_82(freshVar(indexResult.state)) if isinstance(__match_val, Just) else None)) or ((Err(typeError('Index must be Int')) if __match_val is Nothing else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None)) or ((Err(__match_val._field0) if isinstance(__match_val, Err) else None))
def __helper_84(__match_val):
    return (__helper_83(unify(applySubst(__match_val._field0.subst)(__match_val._field0.typ))(TInt)) if isinstance(__match_val, Ok) else None)
def __helper_85(__match_val):
    return (__helper_84(inferExpr(__match_val._field0.state)(__match_val._field0.subst)(index)) if isinstance(__match_val, Ok) else None)